/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq.tables.records;


import net.nyrheim.bricksandmortar.database.jooq.tables.CharacterProfession;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterProfessionRecord extends UpdatableRecordImpl<CharacterProfessionRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 102029676;

    /**
     * Setter for <code>nyrheim.character_profession.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nyrheim.character_profession.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nyrheim.character_profession.profession</code>.
     */
    public void setProfession(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nyrheim.character_profession.profession</code>.
     */
    public String getProfession() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nyrheim.character_profession.experience</code>.
     */
    public void setExperience(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>nyrheim.character_profession.experience</code>.
     */
    public Integer getExperience() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CharacterProfession.CHARACTER_PROFESSION.CHARACTER_ID;
    }

    @Override
    public Field<String> field2() {
        return CharacterProfession.CHARACTER_PROFESSION.PROFESSION;
    }

    @Override
    public Field<Integer> field3() {
        return CharacterProfession.CHARACTER_PROFESSION.EXPERIENCE;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public String component2() {
        return getProfession();
    }

    @Override
    public Integer component3() {
        return getExperience();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public String value2() {
        return getProfession();
    }

    @Override
    public Integer value3() {
        return getExperience();
    }

    @Override
    public CharacterProfessionRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public CharacterProfessionRecord value2(String value) {
        setProfession(value);
        return this;
    }

    @Override
    public CharacterProfessionRecord value3(Integer value) {
        setExperience(value);
        return this;
    }

    @Override
    public CharacterProfessionRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterProfessionRecord
     */
    public CharacterProfessionRecord() {
        super(CharacterProfession.CHARACTER_PROFESSION);
    }

    /**
     * Create a detached, initialised CharacterProfessionRecord
     */
    public CharacterProfessionRecord(Integer characterId, String profession, Integer experience) {
        super(CharacterProfession.CHARACTER_PROFESSION);

        set(0, characterId);
        set(1, profession);
        set(2, experience);
    }
}
