/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq.tables.records;


import net.nyrheim.bricksandmortar.database.jooq.tables.DropTableItem;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DropTableItemRecord extends UpdatableRecordImpl<DropTableItemRecord> implements Record7<Integer, Integer, String, Integer, String, Integer, String> {

    private static final long serialVersionUID = 2112682521;

    /**
     * Setter for <code>nyrheim.drop_table_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.drop_table_id</code>.
     */
    public void setDropTableId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.drop_table_id</code>.
     */
    public Integer getDropTableId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.item_type</code>.
     */
    public void setItemType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.item_type</code>.
     */
    public String getItemType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.amount</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.quality</code>.
     */
    public void setQuality(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.quality</code>.
     */
    public String getQuality() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.chance</code>.
     */
    public void setChance(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.chance</code>.
     */
    public Integer getChance() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>nyrheim.drop_table_item.tool_type</code>.
     */
    public void setToolType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table_item.tool_type</code>.
     */
    public String getToolType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, Integer, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, Integer, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DropTableItem.DROP_TABLE_ITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DropTableItem.DROP_TABLE_ITEM.DROP_TABLE_ID;
    }

    @Override
    public Field<String> field3() {
        return DropTableItem.DROP_TABLE_ITEM.ITEM_TYPE;
    }

    @Override
    public Field<Integer> field4() {
        return DropTableItem.DROP_TABLE_ITEM.AMOUNT;
    }

    @Override
    public Field<String> field5() {
        return DropTableItem.DROP_TABLE_ITEM.QUALITY;
    }

    @Override
    public Field<Integer> field6() {
        return DropTableItem.DROP_TABLE_ITEM.CHANCE;
    }

    @Override
    public Field<String> field7() {
        return DropTableItem.DROP_TABLE_ITEM.TOOL_TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDropTableId();
    }

    @Override
    public String component3() {
        return getItemType();
    }

    @Override
    public Integer component4() {
        return getAmount();
    }

    @Override
    public String component5() {
        return getQuality();
    }

    @Override
    public Integer component6() {
        return getChance();
    }

    @Override
    public String component7() {
        return getToolType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDropTableId();
    }

    @Override
    public String value3() {
        return getItemType();
    }

    @Override
    public Integer value4() {
        return getAmount();
    }

    @Override
    public String value5() {
        return getQuality();
    }

    @Override
    public Integer value6() {
        return getChance();
    }

    @Override
    public String value7() {
        return getToolType();
    }

    @Override
    public DropTableItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DropTableItemRecord value2(Integer value) {
        setDropTableId(value);
        return this;
    }

    @Override
    public DropTableItemRecord value3(String value) {
        setItemType(value);
        return this;
    }

    @Override
    public DropTableItemRecord value4(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public DropTableItemRecord value5(String value) {
        setQuality(value);
        return this;
    }

    @Override
    public DropTableItemRecord value6(Integer value) {
        setChance(value);
        return this;
    }

    @Override
    public DropTableItemRecord value7(String value) {
        setToolType(value);
        return this;
    }

    @Override
    public DropTableItemRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DropTableItemRecord
     */
    public DropTableItemRecord() {
        super(DropTableItem.DROP_TABLE_ITEM);
    }

    /**
     * Create a detached, initialised DropTableItemRecord
     */
    public DropTableItemRecord(Integer id, Integer dropTableId, String itemType, Integer amount, String quality, Integer chance, String toolType) {
        super(DropTableItem.DROP_TABLE_ITEM);

        set(0, id);
        set(1, dropTableId);
        set(2, itemType);
        set(3, amount);
        set(4, quality);
        set(5, chance);
        set(6, toolType);
    }
}
