/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq.tables.records;


import net.nyrheim.bricksandmortar.database.jooq.tables.DropTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DropTableRecord extends UpdatableRecordImpl<DropTableRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1989357220;

    /**
     * Setter for <code>nyrheim.drop_table.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nyrheim.drop_table.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nyrheim.drop_table.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DropTable.DROP_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return DropTable.DROP_TABLE.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public DropTableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DropTableRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DropTableRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DropTableRecord
     */
    public DropTableRecord() {
        super(DropTable.DROP_TABLE);
    }

    /**
     * Create a detached, initialised DropTableRecord
     */
    public DropTableRecord(Integer id, String name) {
        super(DropTable.DROP_TABLE);

        set(0, id);
        set(1, name);
    }
}
