/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq;


import net.nyrheim.bricksandmortar.database.jooq.tables.CharacterProfession;
import net.nyrheim.bricksandmortar.database.jooq.tables.records.CharacterProfessionRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>nyrheim</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CharacterProfessionRecord> KEY_CHARACTER_PROFESSION_PRIMARY = UniqueKeys0.KEY_CHARACTER_PROFESSION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CharacterProfessionRecord> KEY_CHARACTER_PROFESSION_PRIMARY = Internal.createUniqueKey(CharacterProfession.CHARACTER_PROFESSION, "KEY_character_profession_PRIMARY", new TableField[] { CharacterProfession.CHARACTER_PROFESSION.CHARACTER_ID }, true);
    }
}
