/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq;


import net.nyrheim.bricksandmortar.database.jooq.tables.CharacterProfession;


/**
 * Convenience access to all tables in nyrheim
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nyrheim.character_profession</code>.
     */
    public static final CharacterProfession CHARACTER_PROFESSION = CharacterProfession.CHARACTER_PROFESSION;
}
