/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.bricksandmortar.database.jooq.tables;


import java.util.Arrays;
import java.util.List;

import net.nyrheim.bricksandmortar.database.jooq.Keys;
import net.nyrheim.bricksandmortar.database.jooq.Nyrheim;
import net.nyrheim.bricksandmortar.database.jooq.tables.records.CharacterProfessionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterProfession extends TableImpl<CharacterProfessionRecord> {

    private static final long serialVersionUID = 1591423452;

    /**
     * The reference instance of <code>nyrheim.character_profession</code>
     */
    public static final CharacterProfession CHARACTER_PROFESSION = new CharacterProfession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterProfessionRecord> getRecordType() {
        return CharacterProfessionRecord.class;
    }

    /**
     * The column <code>nyrheim.character_profession.character_id</code>.
     */
    public final TableField<CharacterProfessionRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_profession.profession</code>.
     */
    public final TableField<CharacterProfessionRecord, String> PROFESSION = createField(DSL.name("profession"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_profession.experience</code>.
     */
    public final TableField<CharacterProfessionRecord, Integer> EXPERIENCE = createField(DSL.name("experience"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>nyrheim.character_profession</code> table reference
     */
    public CharacterProfession() {
        this(DSL.name("character_profession"), null);
    }

    /**
     * Create an aliased <code>nyrheim.character_profession</code> table reference
     */
    public CharacterProfession(String alias) {
        this(DSL.name(alias), CHARACTER_PROFESSION);
    }

    /**
     * Create an aliased <code>nyrheim.character_profession</code> table reference
     */
    public CharacterProfession(Name alias) {
        this(alias, CHARACTER_PROFESSION);
    }

    private CharacterProfession(Name alias, Table<CharacterProfessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterProfession(Name alias, Table<CharacterProfessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CharacterProfession(Table<O> child, ForeignKey<O, CharacterProfessionRecord> key) {
        super(child, key, CHARACTER_PROFESSION);
    }

    @Override
    public Schema getSchema() {
        return Nyrheim.NYRHEIM;
    }

    @Override
    public UniqueKey<CharacterProfessionRecord> getPrimaryKey() {
        return Keys.KEY_CHARACTER_PROFESSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<CharacterProfessionRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterProfessionRecord>>asList(Keys.KEY_CHARACTER_PROFESSION_PRIMARY);
    }

    @Override
    public CharacterProfession as(String alias) {
        return new CharacterProfession(DSL.name(alias), this);
    }

    @Override
    public CharacterProfession as(Name alias) {
        return new CharacterProfession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterProfession rename(String name) {
        return new CharacterProfession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterProfession rename(Name name) {
        return new CharacterProfession(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
